// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oxxpdgvaarnbhdqewwlh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im94eHBkZ3ZhYXJuYmhkcWV3d2xoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5NjcyODYsImV4cCI6MjA2NTU0MzI4Nn0.ft427dDLOp41k45kmrCEk6kxNDCtH7KdZZ3Qs66jwnk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);